name: base
channels:
  - conda-forge
dependencies:
  - numpy
  - sympy
  - scipy
  - matplotlib
  - slycot
  - control
  - graphviz
  - xdg
  - nodejs
  - widgetsnbextension
  - ipywidgets
  - rise
  - pip
  - pip:
    - -r file:requirements.txt
